GET http://localhost:8000/products/2
Accept: application/json

###
GET http://localhost:8000/products
Accept: application/json

### Criar um pedido ###
POST http://localhost:8000/orders/new
Content-Type: application/json

[
  {
    "productId": 1,
    "amount": 2
  },
  {
    "productId": 2,
    "amount": 1
  }
]

### Obter um pedido por ID ###
GET http://localhost:8000/orders/1
