version: '3.8'

services:
  postgres:
    container_name: products_db
    image: postgres
    environment:
      POSTGRES_DB: public
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - pg_network
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/

  app:
    container_name: axum_diesel
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      RUST_LOG: info
      DATABASE_URL: postgres://root:root@products_db/public
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge