--
-- PostgreSQL database dump
--

-- Dumped from database version 14.7 (Debian 14.7-1.pgdg110+1)
-- Dumped by pg_dump version 14.7 (Ubuntu 14.7-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: product; Type: TABLE; Schema: public; Owner: takeshi
--

CREATE TABLE public.product (
    id integer NOT NULL,
    description character varying(255),
    name character varying(255),
    price double precision NOT NULL
);


--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: takeshi
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productorder; Type: TABLE; Schema: public; Owner: takeshi
--

CREATE TABLE public.productorder (
    id integer NOT NULL,
    amount integer NOT NULL,
    product_id integer,
    shoppingcart_id integer
);


--
-- Name: productorder_id_seq; Type: SEQUENCE; Schema: public; Owner: takeshi
--

ALTER TABLE public.productorder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productorder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shoppingcart; Type: TABLE; Schema: public; Owner: takeshi
--

CREATE TABLE public.shoppingcart (
    id integer NOT NULL,
    total double precision NOT NULL
);


--
-- Name: shoppingcart_id_seq; Type: SEQUENCE; Schema: public; Owner: takeshi
--

ALTER TABLE public.shoppingcart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shoppingcart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: takeshi
--

COPY public.product (id, description, name, price) FROM stdin;
1	Two-Hand Damage: 250-290 Required Strength: 189 +3 to all skills 20% Chance to cast level 18 Tornado on striking	The Grandfather	1500
2	Defense: 184 Required Strength: 167 Required Level: 71 +2 to Shadow Disciplines +30% Faster Run/Walk	Shadow Dancer	1250
3	Defense: 275 Chance to Block: 39% Required Strength: 220 Required Level: 42 +1 to all skills +5% to maximum Cold Resist	Blackoak Shield	900
4	One-Hand Damage: 190-230 Required Strength: 96 Required Level: 67 +3 to Combat Skills +1 to Light Radius	The Redeemer	1800
5	One-Hand Damage: 125-188 Required Strength: 125 Required Level: 45 Indestructible +35% Increased Attack Speed	Doombringer	1400
6	Defense: 1508 Required Strength: 165 Required Level: 85 +1 to all skills +30% Faster Hit Recovery	Arkaine's Valor	3000
7	Damage: 18-42 Required Level: 42 +3 to Sorceress Skills +20% Faster Cast Rate	The Oculus	1100
8	One-Hand Damage: 110-130 Required Strength: 25 Required Level: 85 +2 to Paladin Skills +10% Increased Attack Speed	Azurewrath	2500
9	Required Level: 60 +3 to Trap Skills +20 to Strength	Atma's Scarab	800
10	Two-Hand Damage: 41-482 Required Strength: 114 Required Level: 75 Ignore Target's Defense +10 to Strength	The Reaper's Toll	2800
11	One-Hand Damage: 90-168 Required Strength: 70 Required Level: 48 +200% Enhanced Damage +50 to Life	The Gavel of Pain	750
12	Defense: 350 Required Strength: 174 Required Level: 82 +1 to all skills +30% Faster Hit Recovery	Crown of Ages	4000
13	Two-Hand Damage: 100-242 Required Strength: 167 Required Level: 55 +20 to Strength +20 to Dexterity	Lycander's Flank	900
14	Defense: 1256 Required Strength: 111 Required Level: 85 Cannot be Frozen +30% Faster Hit Recovery	The Gladiator's Bane	2000
15	Defense: 302 Required Strength: 118 Required Level: 42 +2 to Barbarian Skills +20% Open Wounds +3 to Battle Cry	Arreat's Face	1000
16	Throw Damage: 99-180 Required Strength: 122 Required Level: 69 +3 to Javelin and Spear Skills +20% Increased Attack Speed	Thunderstroke	1500
17	Required Level: 45 +150 to Attack Rating +15 to Dexterity +40 to Mana Cold Absorb 20%	Raven Frost	500
18	Damage: 23-50 Required Level: 75 +2 to Necromancer Skills +40% Faster Cast Rate	The Grand Vizier	2000
19	Two-Hand Damage: 125-158 Required Strength: 97 Required Level: 76	Griswold's Redemption	2300
20	Damage: 22-28 Required Level: 66 -50% Target's Defense +2 to all skills +1-123 to Poison Damage	Death's Web	2500
21	One-Hand Damage: 87-222, Two-Hand Damage: 236-525 Required Strength: 189 Required Level: 81 +3 to all skills 20% Chance to cast level 18 Tornado on striking	The Grandfather	3000
22	Two-Hand Damage: 102-466 Required Strength: 225 Required Level: 64 +200% Enhanced Damage +60 to Attack Rating Prevent Monster Heal	Bonehew	1800
23	One-Hand Damage: 38-122 Required Strength: 138 Required Level: 70 Indestructible +50% Increased Attack Speed +200% Enhanced Damage	Death Cleaver	2200
24	Two-Hand Damage: 119-675 Required Strength: 253 Required Level: 87 +30% Increased Attack Speed +200% Enhanced Damage	The Cranium Basher	4500
25	One-Hand Damage: 89-160 Required Strength: 133 Required Level: 63 +2 to all skills +175% Enhanced Damage Adds 222-333 Fire Damage	Demon Limb	800
26	One-Hand Damage: 5-180, Two-Hand Damage: 100-220 Required Strength: 125 Required Level: 82 +3 to Lightning Skills +33% Chance to Cast Level 22 Chain Lightning on Attack	Stormlash	2800
27	Defense: 141 Required Level: 62 +2 to all skills +20 to Strength +2 to all attributes +50 to Life +2 to Mana per Kill	Harlequin Crest	1500
28	Required Level: 76 +10% Faster Run/Walk Lightning Absorb 14-20% 15-20% Better Chance of Getting Magic Items Level 9 Heart of Wolverine (17 Charges) Level 11 Oak Sage (13 Charges)	Wisp Projector	3500
29	Defense: 326 Required Strength: 86 Required Level: 63 +120% Enhanced Defense +30% Faster Hit Recovery +20 to Strength +15 to Dexterity +20 to Energy +15% to Maximum Cold Resist +15% to Maximum Fire Resist	Cerebus' Bite	1200
30	Defense: 380-450 Required Level: 68 +100-150% Enhanced Defense +20 to Strength +20 to Dexterity All Resistances +30-40 Magic Damage Reduced by 7-12	Griswold's Valor	2000
31	One-Hand Damage: 80-160 Required Strength: 125 Required Level: 70 +2 to Paladin Skills +200% Enhanced Damage +50% Damage to Undead Redeem's Aura (Lvl 1)	The Redeemer	2400
\.


--
-- Data for Name: productorder; Type: TABLE DATA; Schema: public; Owner: takeshi
--

COPY public.productorder (id, amount, product_id, shoppingcart_id) FROM stdin;
\.


--
-- Data for Name: shoppingcart; Type: TABLE DATA; Schema: public; Owner: takeshi
--

COPY public.shoppingcart (id, total) FROM stdin;
\.


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: takeshi
--

SELECT pg_catalog.setval('public.product_id_seq', 31, true);


--
-- Name: productorder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: takeshi
--

SELECT pg_catalog.setval('public.productorder_id_seq', 1, false);


--
-- Name: shoppingcart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: takeshi
--

SELECT pg_catalog.setval('public.shoppingcart_id_seq', 1, false);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: takeshi
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: productorder productorder_pkey; Type: CONSTRAINT; Schema: public; Owner: takeshi
--

ALTER TABLE ONLY public.productorder
    ADD CONSTRAINT productorder_pkey PRIMARY KEY (id);


--
-- Name: shoppingcart shoppingcart_pkey; Type: CONSTRAINT; Schema: public; Owner: takeshi
--

ALTER TABLE ONLY public.shoppingcart
    ADD CONSTRAINT shoppingcart_pkey PRIMARY KEY (id);


--
-- Name: productorder fkcah2s03u2wpus5fsjedl0c01j; Type: FK CONSTRAINT; Schema: public; Owner: takeshi
--

ALTER TABLE ONLY public.productorder
    ADD CONSTRAINT fkcah2s03u2wpus5fsjedl0c01j FOREIGN KEY (shoppingcart_id) REFERENCES public.shoppingcart(id);


--
-- Name: productorder fkmeu463lcb0b482pjgjmfwma60; Type: FK CONSTRAINT; Schema: public; Owner: takeshi
--

ALTER TABLE ONLY public.productorder
    ADD CONSTRAINT fkmeu463lcb0b482pjgjmfwma60 FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- PostgreSQL database dump complete
--

